services:
  forntend:
    image: "pwnhcl/frontend:v1"
    ports:
      - "5173:5173"
    networks:
      - mern-network
    container_name: frontend

  backend:
    image: "pwnhcl/backend:v1"
    depends_on:
      - db
    ports:
      - "5050:5050"
    networks:
      - mern-network
    container_name: backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge


volumes:
  mongo-data:
    driver: local 
